language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_script:
  - mysql -e 'create database puresql_test;'
after_script:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
services:
  - mysql
